### ISSUE TITLE
test examples

### ISSUE THREAD

**Issue by wgkwgk** [declare-lab/exemplary-empathy#1]
could i get test examples which have responses like this?
https://raw.githubusercontent.com/declare-lab/MIME/master/output.txt

**Comment by soujanyaporia** [comment]
We shall upload the codes, test results very soon!. Stay tuned :)

**Comment by wgkwgk** [comment]
thank you for replying!!

**Comment by kimwongyuda** [comment]
Congratulations !!!

**Comment by soujanyaporia** [comment]
Thanks!
