### ISSUE TITLE
What version of transformers ？

### ISSUE THREAD

**Issue by cumthxy** [declare-lab/exemplary-empathy#4]
What version of transformers ？

i get the erro when i run CUDA_VISIBLE_DEVICES=0 python train.py --epochs 12 --lr 1e-4 --inference 1656211390

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/22782047/175800977-00f31d38-8583-47b1-8d84-c284c60e569b.png">

**Comment by deepanwayx** [comment]
I have added the `requirements.txt` file. The transformers version is 4.19.2
